tailwind.config = {
        darkMode: "class",
        theme: {
          extend: {
            "colors": {
                    "surface": "#f3fcef",
                    "on-tertiary-container": "#76231b",
                    "on-primary": "#ffffff",
                    "on-tertiary-fixed": "#410001",
                    "surface-container-highest": "#dce5d9",
                    "tertiary-fixed": "#ffdad5",
                    "error-container": "#ffdad6",
                    "on-tertiary-fixed-variant": "#7f2a21",
                    "on-background": "#161d16",
                    "on-secondary-fixed-variant": "#005320",
                    "tertiary": "#9e4036",
                    "tertiary-container": "#ff8b7c",
                    "outline-variant": "#bccbb9",
                    "surface-tint": "#006e2f",
                    "primary-fixed": "#6bff8f",
                    "inverse-surface": "#2a322a",
                    "on-surface-variant": "#3d4a3d",
                    "secondary-fixed-dim": "#62df7d",
                    "inverse-on-surface": "#ebf3e7",
                    "primary-container": "#22c55e",
                    "on-error-container": "#93000a",
                    "on-primary-fixed": "#002109",
                    "on-primary-container": "#004b1e",
                    "on-surface": "#161d16",
                    "surface-container-lowest": "#ffffff",
                    "secondary": "#006e2d",
                    "surface-container-high": "#e2ebde",
                    "on-secondary": "#ffffff",
                    "secondary-fixed": "#7ffc97",
                    "secondary-container": "#7cf994",
                    "tertiary-fixed-dim": "#ffb4a9",
                    "on-secondary-fixed": "#002109",
                    "background": "#f3fcef",
                    "on-tertiary": "#ffffff",
                    "surface-dim": "#d4ddd0",
                    "surface-variant": "#dce5d9",
                    "outline": "#6d7b6c",
                    "error": "#ba1a1a",
                    "inverse-primary": "#4ae176",
                    "primary": "#006e2f",
                    "on-error": "#ffffff",
                    "surface-container": "#e8f0e4",
                    "surface-container-low": "#edf6ea",
                    "on-secondary-container": "#007230",
                    "surface-bright": "#f3fcef",
                    "primary-fixed-dim": "#4ae176",
                    "on-primary-fixed-variant": "#005321"
            },
            "borderRadius": {
                    "DEFAULT": "0.25rem",
                    "lg": "0.5rem",
                    "xl": "0.75rem",
                    "full": "9999px"
            },
            "spacing": {
                    "sm": "8px",
                    "margin": "20px",
                    "gutter": "16px",
                    "xs": "4px",
                    "lg": "24px",
                    "md": "16px",
                    "base": "8px",
                    "xl": "32px"
            },
            "fontFamily": {
                    "label-md": ["Plus Jakarta Sans"],
                    "button": ["Plus Jakarta Sans"],
                    "body-lg": ["Plus Jakarta Sans"],
                    "body-sm": ["Plus Jakarta Sans"],
                    "h1": ["Plus Jakarta Sans"],
                    "h2": ["Plus Jakarta Sans"],
                    "h3": ["Plus Jakarta Sans"],
                    "body-md": ["Plus Jakarta Sans"]
            },
            "fontSize": {
                    "label-md": ["14px", {"lineHeight": "16px", "fontWeight": "600"}],
                    "button": ["16px", {"lineHeight": "20px", "fontWeight": "600"}],
                    "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
                    "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
                    "h1": ["30px", {"lineHeight": "38px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                    "h2": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
                    "h3": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
                    "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}]
            }
          },
        },
      }
